### ISSUE TITLE
Two feeds stopped working

### ISSUE THREAD

**Issue by JSTrostle** [jehna/mastofeeder#13]
I subscribe to two websites, [Techdirt](https://www.techdirt.com) and [GamingOnLinux](https://www.gamingonlinux.com), and both MastoFeeder feeds ([techdirt.com@mastofeeder.com](https://mastofeeder.com/techdirt.com) and [gamingonlinux.com@mastofeeder.com](https://mastofeeder.com/gamingonlinux.com)) have stopped publishing new posts for me. Both websites have new content, but the MastoFeeder feeds for them appear to have stopped working about a week ago. 

The server I'm on is mastodon.online. Both feeds are relatively old (I made them on April 2 and 3). Both still say I'm following them, and I haven't tried to unfollow and then refollow. 

Attached at the bottom is a screenshot of what my page looks like, in case what you see is different.

 I'm not sure what information is/would be relevant, but I'm happy to provide any additional information!

Thanks

![Screenshot from 2023-05-28 22-25-25](https://github.com/jehna/mastofeeder/assets/20631190/939b96c9-dbe3-48fb-8177-6d080109271c)

**Comment by jehna** [comment]
That's weird, seems like my feeds have stopped on 17th of May too 🤔 I'll check if the server has hit some snag

**Comment by jehna** [comment]
Booted the server, let's see if it works now

**Comment by jehna** [comment]
At least my feeds seem to work now, let me know if your feeds started working!

**Comment by JSTrostle** [comment]
Yes! Everything seems to be working. Thank you!

**Comment by hanubeki** [comment]
The server seems to be stopped again 4 days ago

**Comment by hanubeki** [comment]
Probably after #26 is merged, I don't receive any posts from your server.
