### ISSUE TITLE
Can't access public relay

### ISSUE THREAD

**Issue by lc-guy** [jehna/mastofeeder#20]
Seems like there's an SSL issue.

I tried using it yesterday when it was still responding, and it couldn't seem to find the feed with my akkoma instance when doing a search. Same with an instance running locally. Am I doing something wrong, or is it not compatible with pleroma and its forks?

![image](https://github.com/jehna/mastofeeder/assets/5222114/01dd6bc7-ec61-4e07-bace-f2b3bdb2a838)

**Comment by jehna** [comment]
Thanks for reporting! It seems that something has changed as I'm getting a lot of:
```
Public key not found for key https://mastofeeder.com/<feed>/#main-key
```

**Comment by jehna** [comment]
Should be resolved now, there was an issue with fly.io certs
